config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  root :to => 'home#index'

  devise_for :users, :skip => [:registrations, :passwords], :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", sessions: "users/sessions"}
  resources :repos, path: "r", constraints: { id: /[0-9A-Za-z[-][_][\.]]+?\/[0-9A-Za-z[-][_][\.]]+/ } do
    resources :comments, constraints: { id: /[0-9]+/ } do
      post 'like', on: :member
    end
    collection do
      post 'search'
    end
  end

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :comment, length: {minimum: 5}

  belongs_to :user
  belongs_to :repo

  after_commit :notify_mentions, :on => [:create, :update]

  acts_as_votable

  def notify_mentions
    return true # Till mail & background job settings done
    User.where(username: Gitcussion::UsernameExtractor.parse(self.comment)).each do |user|
      UserMailer.new_mention(user, self).deliver
    end
  end

#   handle_asynchronously

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/repo.rb
class Repo < ActiveRecord::Base
  ratyrate_rateable "star"

  serialize :so_data, Hash
  has_many :comments, -> { order(created_at: :desc) }
  def data_hash
    JSON.parse(self.data)
  end

  def to_param
    fullname
  end

  def tag
    name.gsub(" ", "-")
  end

  def score
    average("star") ? average("star").avg : 0.0
  end

  def self.top_commented(count = 10)
    self.select("repos.*, COUNT(repo_id) as comment_count").
        joins(:comments).
        group("repos.id").
        order("comment_count DESC").
        limit(count)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :admin]
  ratyrate_rater
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:github]
  has_many :comments, dependent: :destroy

  acts_as_voter

  def self.from_github(uid)
    User.where(uid: uid).first
  end

  def likes? comment
    self.voted_for? comment
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :recirect_new_domain, if: -> { request.host == "www.gitcuss.com" } 

  def recirect_new_domain
  	redirect_to "http://www.gitcussion.com"
  end

  def after_sign_in_path_for(resource_or_scope)
    if request.env['omniauth.origin']
      request.env['omniauth.origin']
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_repo

  # POST /comments
  # POST /comments.json
  def create
    @comment = @repo.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.js
      else
        format.js
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    if current_user == @comment.user
      @comment.destroy
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js { render text: "You are not authorized", status: :unauthorized }
      end
    end
  end

  def like
    @comment = Comment.find(params[:id])
    if current_user.likes? @comment
      @comment.unliked_by current_user
    else
      @comment.liked_by current_user
    end
    respond_to do |format|
      format.js
    end
  end

  private

    def set_repo
      @repo = Repo.find_by(fullname: params[:repo_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout "application_wide", only: [:index]

  def index
    @top_commented = Repo.top_commented
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]
      obj.reload
      render :json => {status: true, score: obj.score.to_f, id: obj.id}
    else
      render :json => false
    end
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :set_repo, only: [:edit, :update, :destroy]

  def search
    @query = search_params[:query]
    @repos = SearchRepoService.new.call(@query)[:payload]
  end

  # GET /repos/1
  # GET /repos/1.json
  def show
    repo_service = FindRepoService.new.call(params[:id])
    if repo_service[:status] != :error
      @repo = repo_service[:payload]
      @comment = Comment.new
      @owner = @repo.data_hash["owner"]["login"]
      @usernames = User.where(id: @repo.comments.pluck(:user_id)).pluck(:username) << @owner
    end

    respond_to do |format|
      if repo_service[:status] == :error
        format.html { redirect_to root_path, notice: repo_service[:message] }
      else
        format.json
        format.html
      end
    end

  end

  private

  def search_params
    params.permit(:query)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_repo
    @repo = Repo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def repo_params
    params.require(:repo).permit(:name, :fullname, :homepage, :stars, :watchers, :forks, :pushed_at, :html_url, :data)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    auth_data = request.env["omniauth.auth"]
    @user = User.from_github(auth_data['uid'])

    if @user && @user.persisted?
      sign_in_and_redirect @user, :event => :authentication

    else
      @user = User.new(
          email: auth_data['info']['email'],
          password:  Devise.friendly_token[0,20],
          uid: auth_data['uid'],
          provider: "github",
          github_url: auth_data["extra"]["raw_info"]["html_url"],
          avatar_url: auth_data["info"]["image"],
          username: auth_data["info"]["nickname"]
      )
      @user.save
      sign_in_and_redirect @user, :event => :authentication
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def new
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include RailsBootstrapHelpers::Helpers::OptionsHelper

  def fa_icon (icon, options = {})
    options = options.dup

    icon = ERB::Util.html_escape(icon.to_s)
    append_class!(options, "fa-" + icon)

    if options.delete(:invert)
      append_class!(options, "icon-white")
    end

    cls = options[:class]

    "<i class=\"fa #{cls}\"></i>".html_safe
  end

  def login_path
    user_omniauth_authorize_path(:github)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/comments/create.js.erb
<% if @comment.errors.any? %>
    sweetAlert("Oops...", "<%= @comment.errors.full_messages.to_sentence %>", "error");
<% else %>
    $("#comment-input").val("");
    $("#<%= dom_id(@repo) %>").find(".commentList").prepend("<%=escape_javascript(render("repos/comment", :comment => @comment))%>");
    $("#<%= dom_id(@comment) %>").effect('highlight', 500);
    $('time[data-time-ago]').timeago();
<% end %>

app/views/comments/destroy.js.erb
sweetAlert("Success", "Comment was deleted!", "success");
$("#<%= dom_id(@comment) %>").hide();

app/views/comments/like.js.erb
<% if current_user %>
    <% if current_user.likes? @comment %>
      $('span#<%= @comment.id %> a').text('dislike')
    <% else %>
      $('span#<%= @comment.id %> a').text('like')
    <% end %>
<% end %>
$('span.likes_number_for_<%= @comment.id %>').text('<%= @comment.get_likes.size %>')

app/views/home/_repo_item.html.erb
<div class="panel panel-default panel-search-item">
  <div class="panel-heading">
    <div class="panel-title">
      <img class="img-circle pull-left" src="<%= repo.avatar_url %>" alt="" height="65" width="65"/>
      <h3><%= link_to repo.fullname, repo_path(repo.fullname) %></h3>
      <h5><span><%= repo.data_hash["description"] %></span></h5>
    </div>
    <!-- panel toolbar button -->
    <div class="panel-toolbar text-right">
      <span class="label label-default tt" data-title="Stars"><i class="fa fa-star"></i>&nbsp;<%= repo.stars %></span>
      <!--<span class="label label-default tt" data-title="Watchers"><i class="fa fa-eye"></i>&nbsp;<%= repo.watchers %></span>-->
      <span class="label label-default tt" data-title="Open Issues"><i class="fa fa-exclamation-circle"></i>&nbsp;<%= repo.data_hash["open_issues"] %></span>
      <span class="label label-default tt" data-title="Stack Overflow Answered/Total"><i class="fa fa-stack-overflow"></i>&nbsp;<%= repo.so_data["answered_questions"] %>/<%= repo.so_data["total_questions"] %></span>
      <a href="<%= repo_path(repo.fullname) %>">
        <span class="label label-default tt" data-title="Gitcussions"><i class="fa fa-comment-o"></i>&nbsp;<%= repo.comments.count %></span>
      </a>
      <a href="<%= repo.data_hash["html_url"] %>" target="_blank">
        <span class="label label-default tt" data-title="Github Page"><i class="fa fa-github"></i></span>
      </a>

    </div>
  </div>
</div>

app/views/home/index.html.erb
<%
   meta title: "Gitcussion - See Reviews of Github Repositories",
        description: "Reviews, comments and details about Github repositories",
        author: "Mehmet Beydogan",
        og: {
                image: "http://www.gitcussion.com/gitcuss.png",
                title: "Gitcussion - See Reviews of Github Repositories",
                description: "Reviews, comments and details about Github repositories",
                url: root_url
        }

%>

<section class="featured">
  <div class="container">
    <div class="row mar-bot10">
      <div class="col-md-6 col-md-offset-3">

        <div class="align-center">
          <h2 class="slogan">See Reviews of Github Repositories</h2>
          <div class="search-form mar-top30">
            <%= form_tag search_repos_path do %>
                <div class="input-group">
                  <input type="text" class="form-control" name="query" placeholder="Search for a repository">
                  <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit">Go!</button>
                  </span>
                </div><!-- /input-group -->
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="container pad-top20">
  <div class="row">
    <div class="col-lg-12">
      <h3>Most Commented Repositories</h3>
      <% @top_commented.each do |repo| %>
          <%= render 'repo_item', repo: repo %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="blog-footer">
  <p>
    <a class="btn btn-info" href="<%= repo_path("beydogan/gitcussion") %>"><i class="fa fa-comment-o"></i> leave a feedback</a>
  </p>
  <p>Built with Ruby on Rails by <a href="http://mehmet.pw">Mehmet Beydogan</a>.</p>
  <p class="social">
    <a href="https://twitter.com/gitcussion"><i class="fa fa-twitter"></i></a>
    <a href="https://github.com/beydogan/gitcussion"><i class="fa fa-github"></i></a>
  </p>
  <p><a href="https://www.gitcussion.com">Gitcussion</a> is licensed with Apache 2.0. Source code is available on <a href="https://github.com/beydogan/gitcussion" target="_blank">GitHub</a></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>
<script>
    <% if Rails.env.production?  %>
        var _gaq = _gaq || [];
        _gaq.push(['_setDomainName', "www.gitcuss.com"]);

        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-58177008-1', 'auto');
        ga('send', 'pageview');
    <% end %>
</script>

app/views/layouts/_head_tag.html.erb
<head>
  <%= metamagic site: "Gitcussion", title: -> { title.present? ? (title.include?(site) ? title : "#{title} - #{site}") : site }%>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_tag do %>
      login_path = "<%= login_path %>"
  <% end %>
</head>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-static-top">
  <div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>"><i class="fa fa-github"></i>&nbsp;Gitcussion</a>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li><a href="#"><%= current_user.username %></a></li>
            <li><%= link_to "Logout",  destroy_user_session_path, :method => :delete  %></li>
        <% else %>
            <li><a href="<%= user_omniauth_authorize_path(:github) %>" data-no-turbolink>Sign in with Github</a></li>
        <% end %>
    </ul>
  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <%= render "layouts/head_tag" %>
    <body>

    <%= render 'layouts/header' %>

    <div class="container pt20">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>

    </body>

</html>

app/views/layouts/application_wide.html.erb
<!DOCTYPE html>
<html>
    <%= render "layouts/head_tag" %>
    <body>

        <%= render 'layouts/header' %>

            <%= yield %>

        <%= render 'layouts/footer' %>
    </body>
</html>

app/views/repos/_comment.html.erb
<li id="<%= dom_id(comment) %>">
  <div class="commenterImage">
    <a href="<%= comment.user.github_url  %>"><img src="<%= comment.user.avatar_url %>"></a>
  </div>
  <div class="commentText">
    <p class=""><%= comment.comment %></p>
    <span class="like sub-text" id="<%= comment.id %>">
      <%= link_to like_repo_comment_path(comment.repo, comment), method: :post, remote: true do %>
        <%= current_user.likes?(comment) ? 'dislike' : 'like' %>
      <% end if current_user %>
      <i class="fa fa-thumbs-up"></i><span class="likes_number_for_<%= comment.id %>"><%= comment.get_likes.size %></span>
    </span>
    <span class="date sub-text"><%= timeago_tag comment.created_at, :nojs => true, :limit => 1000.days.ago %> </span>
    <span class="sub-text">by <%= link_to comment.user.username, comment.user.github_url %>
      <% if @owner == comment.user.username %>
        <div class="label label-warning">Owner</div>
      <% end %>
    </span>
    <span class="sub-text pull-right"><%= link_to "delete", repo_comment_path(repo_id: @repo.fullname, id: comment.id), method: :delete, remote: true if comment.user == current_user %></span>
  </div>
</li>

app/views/repos/_comment_form.html.erb
<%= simple_form_for [@repo, @comment], remote: true do |f| %>
    <div class="input-group">
      <%= f.text_field :comment, class: "form-control", id: "comment-input", placeholder: "Say something about #{@repo.name}" %>
      <span class="input-group-btn">
        <%= f.submit class: "btn btn-success", value: "Commit" %>
        </span>
    </div><!-- /input-group -->
<% end %>

<script>
    $(function () {
        data = <%= raw @usernames.uniq.compact %>;
        $('#comment-input').atwho({at: "@", 'data': data});
    });
</script>

app/views/repos/_comment_list.html.erb
<h4>Comments about <strong><%= @repo.name %></strong></h4>
<ul class="commentList">
    <% comments.each do |comment| %>
        <%= render "comment", comment: comment %>
    <% end %>
</ul>

app/views/repos/_search_item.html.erb
<div class="panel panel-default panel-search-item">
  <div class="panel-heading">
    <div class="panel-title">
      <img class="img-circle pull-left" src="<%= repo.avatar_url %>" alt="" height="65" width="65"/>
      <h3><%= link_to repo.fullname, repo_path(repo.fullname) %></h3>
      <h5><span><%= repo.data_hash["description"] %></span></h5>
    </div>
    <!-- panel toolbar button -->
    <div class="panel-toolbar text-right">
      <span class="label label-default tt" data-title="Stars"><i class="fa fa-star"></i>&nbsp;<%= repo.stars %></span>
      <!--<span class="label label-default tt" data-title="Watchers"><i class="fa fa-eye"></i>&nbsp;<%= repo.watchers %></span>-->
      <span class="label label-default tt" data-title="Open Issues"><i class="fa fa-exclamation-circle"></i>&nbsp;<%= repo.data_hash["open_issues"] %></span>
    </div>
  </div>
</div>

app/views/repos/search.html.erb
<%
   meta title: "Search results for #{@query}"
%>

<div class="row">
    <div class="col-lg-12">
      <h2 class="text-primary">Search results for <i><%= @query %></i></h2>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
      <% @repos.each do |repo| %>
          <%= render 'search_item', repo: repo %>
      <% end %>
    </div>
</div>

app/views/repos/show.html.erb
<%
   meta title: "#{@repo.name.humanize} on Gitcussion",
        description: "Reviews, comments and details about #{@repo.name}",
        keywords: [@repo.name, @repo.fullname],
        og: {
                image: "http://www.gitcuss.com/gitcussion.png",
                title: "#{@repo.name.humanize} on Gitcussion",
                description: "Reviews, comments and details about #{@repo.name}",
                url: repo_url(@repo.fullname)
        }

%>

<div class="panel panel-default panel-search-item repo-item" id="<%= dom_id(@repo) %>">
  <div class="panel-heading">
    <div class="panel-title">
      <img class="img-circle pull-left" src="<%= @repo.avatar_url %>" alt="" height="65" width="65"/>
      <h3><%= link_to @repo.fullname, repo_path(@repo.fullname) %></h3>
      <h5><span><%= @repo.data_hash["description"] %></span></h5>
    </div>
    <!-- panel toolbar button -->
    <div class="panel-toolbar text-right">
      <span class="label label-default tt" data-title="Stars"><i class="fa fa-star"></i>&nbsp;<%= @repo.stars %></span>
      <!--<span class="label label-default tt" data-title="Watchers"><i class="fa fa-eye"></i>&nbsp;<%= @repo.watchers %></span>-->
      <span class="label label-default tt" data-title="Open Issues"><i class="fa fa-exclamation-circle"></i>&nbsp;<%= @repo.data_hash["open_issues"] %></span>
      <span class="label label-default tt" data-title="Stack Overflow Answered/Total"><i class="fa fa-stack-overflow"></i>&nbsp;<%= @repo.so_data["answered_questions"] %>/<%= @repo.so_data["total_questions"] %></span>

      <span class="label label-default tt" data-title="Average Score"><i class="fa fa-star"></i>&nbsp;<span class="score"><%= @repo.score %></span></span>



      <a href="<%= @repo.data_hash["html_url"] %>" target="_blank">
        <span class="label label-default tt" data-title="Github Page"><i class="fa fa-github"></i></span>
      </a>

      <span class="">
              <%= rating_for @repo, "star", disable_after_rate: false %>
      </span>
    </div>
  </div>
  <div class="panel-body readme">
    <div class="readme-content">
      <%= @repo.readme.try(:html_safe) %>
    </div>
  </div>
  <div class="panel-footer">
    <%= render 'comment_list', comments: @repo.comments %>
    <% if current_user %>
        <%= render 'comment_form' %>
    <% else %>
        <div class="alert alert-warning" role="">First, you have to <a href="<%= user_omniauth_authorize_path(:github) %>">login</a> to send a comment.</div>
    <% end %>
  </div>
</div>